version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - './:/app'
      - '.docker/site.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - fpm
    links:
      - fpm

  fpm:
    image: php:8.1-fpm
    volumes:
      - './:/app'

  varnish:
    image: varnish:latest
    depends_on:
      - nginx
    volumes:
      - .docker/varnish.vcl:/etc/varnish/default.vcl
    links:
      - nginx
    ports:
      - '5000:80'
