version: '3.7'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    volumes:
      - mysql_local:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mysql_local:
    driver: local
