version: '3.7'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    volumes:
      - mysql_local:/var/lib/mysql
    ports:
      - '3306:3306'

  redis:
    image: redis:6.2-alpine3.14
    ports:
      - '6379:6379'

  nginx:
    image: nginx:latest
    ports:
      - '8000:80'
    volumes:
      - './:/app'
      - '.docker/nginx/site.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - fpm
    links:
      - fpm

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - '9113:9113'
    command:
      - -nginx.scrape-uri
      - http://nginx:8080/stub_status
    depends_on:
      - prometheus
      - nginx
    links:
      - nginx
      - prometheus

  fpm:
    image: php:8.1-fpm
    volumes:
      - './:/app'

  prometheus:
    image: bitnami/prometheus
    ports:
      - '9090:9090'
    volumes:
      - '.docker/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml'

volumes:
  mysql_local:
    driver: local
