version: '3.7'

services:
  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    volumes:
      - mysql_local:/var/lib/mysql
    ports:
      - '3306:3306'

  redis:
    image: redis:6.2-alpine3.14
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:3.9-management
    ports: [ 5672, 15672 ]

  blackfire:
    image: blackfire/blackfire
    env_file: .env.local
    ports: [ 8707 ]

  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]

volumes:
  mysql_local:
    driver: local
